export const QUOTES = [
  { text: 'स्वाध्यायान्मा प्रमदः', translation: 'Never neglect self-study.', source: 'Taittiriya Upanishad' },
  { text: 'The quality of your practice determines the quality of your life.', source: 'Carnatic tradition' },
  { text: 'ॐ तत् सत्', translation: 'That which is — is truth.', source: 'Bhagavad Gita 17.23' },
  { text: 'You do not rise to the level of your goals. You fall to the level of your systems.', source: 'James Clear' },
  { text: 'सा विद्या या विमुक्तये', translation: 'That alone is true knowledge which liberates.', source: 'Vishnu Purana' },
  { text: 'Nādam is not sound. It is consciousness vibrating.', source: 'Carnatic philosophy' },
  { text: 'Every riyaz session is a brick in a temple you will never see completed — and that is the point.', source: 'Svadhyaya' },
  { text: 'The practice never pauses. It only scales down.', source: 'Svadhyaya · Spiritual chapter' },
  { text: 'Sangeetam is not just practice. It is seva. Show up for it as you would for God.', source: 'Carnatic tradition' },
  { text: 'Financial freedom is not a number. It is a daily practice.', source: 'Svadhyaya · Artha' },
  { text: 'यदा यदा हि धर्मस्य ग्लानिर्भवति भारत', translation: 'Whenever dharma declines, I arise.', source: 'Bhagavad Gita 4.7' },
  { text: 'The man who wakes at 5:30 and sits in silence is building something the world cannot see — yet.', source: 'Svadhyaya' },
  { text: 'Compound interest works on habits the same way it works on money.', source: 'James Clear' },
  { text: 'Read to become, not to know.', source: 'Svadhyaya · Vidyā' },
  { text: 'The walk is not exercise. It is the threshold between night and day.', source: 'Svadhyaya · Sharīram' },
  { text: 'अहिंसा परमो धर्मः', translation: 'Non-violence is the highest dharma.', source: 'Mahabharata' },
  { text: 'Tech is the vehicle. Music is the destination.', source: 'Svadhyaya · Nādam' },
  { text: 'Ecstatic and humbler at 45.', source: 'The north star' },
  { text: 'Win the morning, win the day.', source: 'Tim Ferriss' },
  { text: 'The two-minute rule: if starting feels hard, just start for two minutes.', source: 'David Allen' },
  { text: 'शरीरमाद्यं खलु धर्मसाधनम्', translation: 'The body is the primary instrument of dharma.', source: 'Kalidasa' },
  { text: 'Every note you sing correctly is a prayer answered.', source: 'Carnatic tradition' },
  { text: 'The debt closes. The corpus grows. They cannot both be true — until suddenly they are.', source: 'Svadhyaya · Artha' },
  { text: 'Begin with the end in mind.', source: 'Stephen R. Covey' },
  { text: 'Sow a thought, reap a habit; sow a habit, reap a character; sow a character, reap a destiny.', source: 'Ancient wisdom' },
  { text: 'ध्यानमूलं गुरोर्मूर्तिः', translation: 'The root of meditation is the Guru\'s form.', source: 'Guru Gita' },
  { text: 'The 300-book library exists to be read, not owned.', source: 'Svadhyaya · Vidyā' },
  { text: 'Your daughter is watching. What kind of man do you want her to see?', source: 'Svadhyaya' },
  { text: 'Never miss twice. In any area. Ever.', source: 'The one rule' },
  { text: 'Invisible work must become visible. Document it before deployment, not after.', source: 'Svadhyaya · Karma' },
]
